name: Run Maven Tests on Push

on:
  push:
    branches:
      - '**'  # Runs on every push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Maven tests
        run: mvn clean test
